# Generated by Django 4.2.2 on 2023-07-04 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pereval.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Долгота')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=10, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=10, null=True, verbose_name='Весна')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otc', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+799999999'. Максимум 15 цифр.", regex='^\\+\\d{6,15}$')], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=8)),
                ('beauty_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название препятствия')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название вершины')),
                ('other_titles', models.CharField(blank=True, max_length=50, null=True, verbose_name='Другое название')),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coords', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='pereval.user')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.ImageField(blank=True, null=True, upload_to=pereval.models.get_path_upload_photos, verbose_name='Изображение')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('pereval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pereval')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
