# Generated by Django 4.2.2 on 2023-07-06 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+799999999'. Максимум 15 цифр.", regex='^\\+?[\\d\\s]{6,15}$')], verbose_name='Номер телефона'),
        ),
    ]
